name: Windows

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile
      run: |
        echo "build start"
        dir
        cl /Fe:sqinn.exe src\*.c
        dir
        echo "executing test"
        .\sqinn.exe test
        md dist
        copy sqinn.exe dist
        echo "build done"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-windows
        path: dist

